Repository sromerodiaz-dc/proyecto-programacion, pull requests merged in 2024-05, with the labels that each got.

#9 prueba workflow de pullrequestYML
  .github/workflows/pull_request_closed.yml
Labels: bug

#10 Creación de un workflow
  .github/workflows/issues.yml
Labels: bug

#7 Issue 1 - # Key Listeners y Graphics - Comienzo del desarrollo
  Assets/player/downWalking1.png
  Assets/player/downWalking2.png
  Assets/player/frontStanding.png
  Assets/player/leftStanding.png
  Assets/player/leftWalking1.png
  Assets/player/leftWalking2.png
  Assets/player/rightStanding.png
  Assets/player/rightWalking1.png
  Assets/player/rightWalking2.png
  Assets/player/upWalkingBehind1.png
  Assets/player/upWalkingBehind2.png
  README.MD
  images/componente2DCreado.png
  images/moveTemprano.gif
  images/muestraSprites.gif
  src/ENTITY/Entity.java
  src/ENTITY/Player.java
  src/FX/KeyManager.java
  src/FX/Main.java
  src/FX/TeisPanel.java
  src/GUI/ventana.java
  src/Main.java
  src/TeisPanel.java
  src/ventana.java
Labels: enhancement

#14 Tilemap editor
  src/EDITOR/EMPTYMAP/CeldaVacia.java
  src/EDITOR/EMPTYMAP/VacioPanel.java
  src/EDITOR/FX/GuardarMapa.java
  src/EDITOR/FX/Main.java
  src/EDITOR/FX/SpriteLoader.java
  src/EDITOR/FX/SpriteUtils.java
  src/EDITOR/GUI/GUI.java
  src/EDITOR/SELECTPANEL/Celda.java
  src/EDITOR/SELECTPANEL/GridPanel.java
  src/EDITOR/SELECTPANEL/Tile.java
  src/EDITOR/WORLD/CeldaWorld.java
  src/EDITOR/WORLD/WorldMap.java
Labels: testing

#23 Issue 20 objetos e interacción y sonidos
  Assets/effects/normalito.wav
  Assets/effects/recogeobjetos.wav
  Assets/maps/mapaPrueba.txt
  Assets/maps/worldExample.txt
  Assets/objects/busVitrasa.png
  Assets/objects/busVitrasa2.png
  Assets/objects/contenedorVigo.png
  Assets/objects/passvigoPlus.png
  META-INF/MANIFEST.MF
  README.MD
  out/artifacts/proyecto_jar/proyecto.jar
  src/EDITOR/FX/SpriteUtils.java
  src/EDITOR/GUI/GUI.java
  src/GAME/EFFECT/Sound.java
  src/GAME/EFFECT/UserInterface.java
  src/GAME/ENTITY/CollisionCheck.java
  src/GAME/ENTITY/Entity.java
  src/GAME/ENTITY/Player.java
  src/GAME/FX/Main.java
  src/GAME/GAME/GameController.java
  src/GAME/GAME/Main.java
  src/GAME/GAME/TeisPanel.java
  src/GAME/GPHICS/Pieza.java
  src/GAME/GPHICS/PiezaManager.java
  src/GAME/GUI/ventana.java
  src/GAME/OBJECT/OBJS/BusVitrasa.java
  src/GAME/OBJECT/OBJS/Container.java
  src/GAME/OBJECT/OBJS/Passvigo.java
  src/GAME/OBJECT/OBJS/Puerta.java
  src/GAME/OBJECT/ObjectGame.java
  src/GAME/OBJECT/ObjectPlacer.java
  src/GAME/TEST/TestEntity.java
Labels: documentation, Dentro de poco...
